index:
  banner_img: /img/bg/math.jpg
  banner_img_height: 100
post:
  banner_img: /img/default.png
  banner_img_height: 70
  default_index_img:
archive:
  banner_img: /img/default.png
  banner_img_height: 80
category:
  banner_img: /img/default.png
  banner_img_height: 80
tag:
  banner_img: /img/default.png
  banner_img_height: 80
about:
  banner_img: /img/default.png
  banner_img_height: 80
links:
  banner_img: /img/default.png
  banner_img_height: 80
